-- ============================================================================
-- canonical-baseline.sql
-- Tirak tirak-payments-v1 canonical baseline (T-028).
--
-- Generated by scripts/migrations/generate-canonical-baseline.mjs.
-- Content is a pure, deterministic concatenation of the source files below,
-- in the order listed. Do not edit by hand; regenerate instead.
--
-- Applied exactly once and recorded as exactly one d1_migrations row
-- (docs/contracts/tirak-payments-v1/migration-strategy.md).
--
-- Excluded by strategy: 004_mobile_app_features.sql (quarantined legacy),
-- 009_booking_scoped_chat.sql (quarantined destructive rename), and
-- 008/010/011 (applied separately through the Wrangler migration ledger).
--
-- Provenance (source file => sha256 of its raw bytes):
--   001_initial_schema.sql => e1cf3f7a300a45269b52ddccc415c00f59f7b15a17227e3756f0b55e0e0cdc0d
--   002_add_indexes.sql => 95f0da88d26f1380ad03ab99fe5c347d2d2cbe1080be99609427447de5283556
--   003_add_analytics_tables.sql => 27c807f5b9c361df16b716bc271ac4158aaa5f488ac75eb6b791fc23a9a449dd
--   004_background_jobs_tables.sql => eb5b4837f46f83f35d0df82bd04ade1921eed32e0cd15de1493c60553aedb738
--   005_muse_ai_foundation.sql => 8f898066af3dcad79b56bfd3f397d6066ec3d7b8f66b6dbf1cc4ef2f7066bd5f
--   006_referrals_tirak_coins.sql => dab4a56f1f78022982601cf6cd018a813660c73f9572713e4ad0cfe833c2130d
--   007_registration_profile_persistence.sql => 79d7b7a94d9cd40d9e161191f293cc143e68f8aa3132bc727f3072c6e1b1857f
-- ============================================================================

-- ---- begin: 001_initial_schema.sql (sha256: e1cf3f7a300a45269b52ddccc415c00f59f7b15a17227e3756f0b55e0e0cdc0d) ----
-- Initial schema migration for Tirak platform
-- Migration: 001_initial_schema.sql

-- Users table (core user data)
CREATE TABLE users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    phone TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    user_type TEXT NOT NULL CHECK (user_type IN ('customer', 'supplier', 'admin')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('active', 'suspended', 'pending')),
    email_verified BOOLEAN DEFAULT FALSE,
    phone_verified BOOLEAN DEFAULT FALSE,
    preferred_language TEXT DEFAULT 'en' CHECK (preferred_language IN ('en', 'th')),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_login_at DATETIME
);

-- Supplier profiles
CREATE TABLE supplier_profiles (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    display_name TEXT NOT NULL,
    bio TEXT,
    profile_images TEXT, -- JSON array of image URLs
    categories TEXT, -- JSON array of category IDs
    regions TEXT, -- JSON array of region IDs
    spoken_languages TEXT, -- JSON array of language codes
    rating_average REAL DEFAULT 0.0,
    rating_count INTEGER DEFAULT 0,
    verification_status TEXT DEFAULT 'pending' CHECK (verification_status IN ('pending', 'verified', 'rejected')),
    subscription_status TEXT DEFAULT 'inactive' CHECK (subscription_status IN ('active', 'inactive', 'expired')),
    subscription_tier TEXT DEFAULT 'basic' CHECK (subscription_tier IN ('basic', 'premium', 'enterprise')),
    subscription_expires_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Customer profiles
CREATE TABLE customer_profiles (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    display_name TEXT NOT NULL,
    profile_image TEXT,
    preferences TEXT, -- JSON object for user preferences
    loyalty_points INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Services offered by suppliers
CREATE TABLE supplier_services (
    id TEXT PRIMARY KEY,
    supplier_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    price_min REAL NOT NULL,
    price_max REAL NOT NULL,
    currency TEXT DEFAULT 'THB',
    duration_hours INTEGER NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Supplier availability
CREATE TABLE supplier_availability (
    id TEXT PRIMARY KEY,
    supplier_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6), -- 0 = Sunday
    start_time TEXT NOT NULL, -- HH:MM format
    end_time TEXT NOT NULL, -- HH:MM format
    is_available BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(supplier_id, day_of_week)
);

-- Chat rooms
CREATE TABLE chat_rooms (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL REFERENCES users(id),
    supplier_id TEXT NOT NULL REFERENCES users(id),
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'closed', 'archived')),
    last_message_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(customer_id, supplier_id)
);

-- Chat messages
CREATE TABLE chat_messages (
    id TEXT PRIMARY KEY,
    room_id TEXT NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    sender_id TEXT NOT NULL REFERENCES users(id),
    message_type TEXT NOT NULL CHECK (message_type IN ('text', 'image', 'system')),
    content TEXT,
    image_url TEXT,
    metadata TEXT, -- JSON for additional message data
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Bookings
CREATE TABLE bookings (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL REFERENCES users(id),
    supplier_id TEXT NOT NULL REFERENCES users(id),
    service_id TEXT NOT NULL REFERENCES supplier_services(id),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),
    scheduled_at DATETIME NOT NULL,
    duration INTEGER NOT NULL, -- in minutes
    total_amount REAL NOT NULL,
    currency TEXT DEFAULT 'THB',
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Reviews and ratings
CREATE TABLE reviews (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL REFERENCES bookings(id),
    reviewer_id TEXT NOT NULL REFERENCES users(id),
    reviewee_id TEXT NOT NULL REFERENCES users(id),
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    is_public BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(booking_id, reviewer_id)
);

-- Categories (for services)
CREATE TABLE categories (
    id TEXT PRIMARY KEY,
    name_en TEXT NOT NULL,
    name_th TEXT NOT NULL,
    description_en TEXT,
    description_th TEXT,
    icon_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    sort_order INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Regions (geographical areas)
CREATE TABLE regions (
    id TEXT PRIMARY KEY,
    name_en TEXT NOT NULL,
    name_th TEXT NOT NULL,
    country_code TEXT DEFAULT 'TH',
    is_active BOOLEAN DEFAULT TRUE,
    sort_order INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- User sessions (for tracking active sessions)
CREATE TABLE user_sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    refresh_token_hash TEXT NOT NULL,
    device_id TEXT,
    ip_address TEXT,
    user_agent TEXT,
    expires_at DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_active_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ---- end: 001_initial_schema.sql ----

-- ---- begin: 002_add_indexes.sql (sha256: 95f0da88d26f1380ad03ab99fe5c347d2d2cbe1080be99609427447de5283556) ----
-- Performance indexes migration
-- Migration: 002_add_indexes.sql

-- User table indexes
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_phone ON users(phone);
CREATE INDEX idx_users_user_type ON users(user_type);
CREATE INDEX idx_users_status ON users(status);
CREATE INDEX idx_users_created_at ON users(created_at);

-- Supplier profile indexes
CREATE INDEX idx_supplier_profiles_verification_status ON supplier_profiles(verification_status);
CREATE INDEX idx_supplier_profiles_subscription_status ON supplier_profiles(subscription_status);
CREATE INDEX idx_supplier_profiles_rating_average ON supplier_profiles(rating_average);
CREATE INDEX idx_supplier_profiles_created_at ON supplier_profiles(created_at);

-- Service indexes
CREATE INDEX idx_supplier_services_supplier_id ON supplier_services(supplier_id);
CREATE INDEX idx_supplier_services_is_active ON supplier_services(is_active);
CREATE INDEX idx_supplier_services_price_min ON supplier_services(price_min);
CREATE INDEX idx_supplier_services_price_max ON supplier_services(price_max);

-- Availability indexes
CREATE INDEX idx_supplier_availability_supplier_id ON supplier_availability(supplier_id);
CREATE INDEX idx_supplier_availability_day_of_week ON supplier_availability(day_of_week);
CREATE INDEX idx_supplier_availability_is_available ON supplier_availability(is_available);

-- Chat room indexes
CREATE INDEX idx_chat_rooms_customer_id ON chat_rooms(customer_id);
CREATE INDEX idx_chat_rooms_supplier_id ON chat_rooms(supplier_id);
CREATE INDEX idx_chat_rooms_status ON chat_rooms(status);
CREATE INDEX idx_chat_rooms_last_message_at ON chat_rooms(last_message_at);
CREATE INDEX idx_chat_rooms_created_at ON chat_rooms(created_at);

-- Chat message indexes
CREATE INDEX idx_chat_messages_room_id ON chat_messages(room_id);
CREATE INDEX idx_chat_messages_sender_id ON chat_messages(sender_id);
CREATE INDEX idx_chat_messages_message_type ON chat_messages(message_type);
CREATE INDEX idx_chat_messages_created_at ON chat_messages(created_at);

-- Booking indexes
CREATE INDEX idx_bookings_customer_id ON bookings(customer_id);
CREATE INDEX idx_bookings_supplier_id ON bookings(supplier_id);
CREATE INDEX idx_bookings_service_id ON bookings(service_id);
CREATE INDEX idx_bookings_status ON bookings(status);
CREATE INDEX idx_bookings_scheduled_at ON bookings(scheduled_at);
CREATE INDEX idx_bookings_created_at ON bookings(created_at);

-- Review indexes
CREATE INDEX idx_reviews_booking_id ON reviews(booking_id);
CREATE INDEX idx_reviews_reviewer_id ON reviews(reviewer_id);
CREATE INDEX idx_reviews_reviewee_id ON reviews(reviewee_id);
CREATE INDEX idx_reviews_rating ON reviews(rating);
CREATE INDEX idx_reviews_is_public ON reviews(is_public);
CREATE INDEX idx_reviews_created_at ON reviews(created_at);

-- Category indexes
CREATE INDEX idx_categories_is_active ON categories(is_active);
CREATE INDEX idx_categories_sort_order ON categories(sort_order);

-- Region indexes
CREATE INDEX idx_regions_country_code ON regions(country_code);
CREATE INDEX idx_regions_is_active ON regions(is_active);
CREATE INDEX idx_regions_sort_order ON regions(sort_order);

-- Session indexes
CREATE INDEX idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX idx_user_sessions_expires_at ON user_sessions(expires_at);
CREATE INDEX idx_user_sessions_last_active_at ON user_sessions(last_active_at);

-- Composite indexes for common queries
CREATE INDEX idx_suppliers_search ON supplier_profiles(verification_status, subscription_status, rating_average);
CREATE INDEX idx_chat_messages_room_time ON chat_messages(room_id, created_at);
CREATE INDEX idx_bookings_supplier_status ON bookings(supplier_id, status);
CREATE INDEX idx_reviews_reviewee_public ON reviews(reviewee_id, is_public);

-- ---- end: 002_add_indexes.sql ----

-- ---- begin: 003_add_analytics_tables.sql (sha256: 27c807f5b9c361df16b716bc271ac4158aaa5f488ac75eb6b791fc23a9a449dd) ----
-- Analytics and moderation tables migration
-- Migration: 003_add_analytics_tables.sql

-- Analytics events
CREATE TABLE analytics_events (
    id TEXT PRIMARY KEY,
    event_type TEXT NOT NULL,
    user_id TEXT REFERENCES users(id),
    session_id TEXT,
    properties TEXT, -- JSON object
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    ip_address TEXT,
    user_agent TEXT
);

-- Content moderation queue
CREATE TABLE moderation_queue (
    id TEXT PRIMARY KEY,
    content_type TEXT NOT NULL CHECK (content_type IN ('message', 'profile', 'review', 'image')),
    content_id TEXT NOT NULL,
    user_id TEXT NOT NULL REFERENCES users(id),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    flagged_reason TEXT,
    moderator_id TEXT REFERENCES users(id),
    moderator_notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    reviewed_at DATETIME
);

-- Analytics indexes
CREATE INDEX idx_analytics_events_event_type ON analytics_events(event_type);
CREATE INDEX idx_analytics_events_user_id ON analytics_events(user_id);
CREATE INDEX idx_analytics_events_timestamp ON analytics_events(timestamp);
CREATE INDEX idx_analytics_events_session_id ON analytics_events(session_id);

-- Moderation indexes
CREATE INDEX idx_moderation_queue_content_type ON moderation_queue(content_type);
CREATE INDEX idx_moderation_queue_user_id ON moderation_queue(user_id);
CREATE INDEX idx_moderation_queue_status ON moderation_queue(status);
CREATE INDEX idx_moderation_queue_priority ON moderation_queue(priority);
CREATE INDEX idx_moderation_queue_created_at ON moderation_queue(created_at);
CREATE INDEX idx_moderation_queue_moderator_id ON moderation_queue(moderator_id);

-- ---- end: 003_add_analytics_tables.sql ----

-- ---- begin: 004_background_jobs_tables.sql (sha256: eb5b4837f46f83f35d0df82bd04ade1921eed32e0cd15de1493c60553aedb738) ----
-- Migration 004: Background Jobs and Analytics Tables
-- This migration adds tables for moderation, analytics, and notification processing

-- Moderation Results Table
CREATE TABLE IF NOT EXISTS moderation_results (
    id TEXT PRIMARY KEY,
    content_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    job_type TEXT NOT NULL CHECK (job_type IN ('text_analysis', 'image_analysis', 'profile_review', 'manual_review')),
    action TEXT NOT NULL CHECK (action IN ('approve', 'flag', 'remove', 'escalate', 'suspend_user')),
    confidence REAL NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    reasons TEXT NOT NULL, -- JSON array of reasons
    severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    ai_analysis TEXT, -- JSON object with AI analysis results
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Flagged Content Table
CREATE TABLE IF NOT EXISTS flagged_content (
    id TEXT PRIMARY KEY,
    content_id TEXT NOT NULL,
    content_type TEXT NOT NULL DEFAULT 'message',
    reasons TEXT NOT NULL, -- JSON array of reasons
    flagged_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TEXT,
    resolved_by TEXT,
    resolution_action TEXT,
    FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
);

-- Manual Review Queue Table
CREATE TABLE IF NOT EXISTS manual_review_queue (
    id TEXT PRIMARY KEY,
    content_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    job_type TEXT NOT NULL,
    ai_result TEXT, -- JSON object with AI analysis
    priority TEXT NOT NULL CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_review', 'completed', 'escalated')),
    assigned_to TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL
);

-- Analytics Events Table (Raw Events)
CREATE TABLE IF NOT EXISTS analytics_events (
    id TEXT PRIMARY KEY,
    event_type TEXT NOT NULL,
    user_id TEXT NOT NULL,
    properties TEXT NOT NULL, -- JSON object with event properties
    timestamp TEXT NOT NULL,
    session_id TEXT,
    device_info TEXT, -- JSON object with device information
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Daily Metrics Table (Aggregated)
CREATE TABLE IF NOT EXISTS daily_metrics (
    id TEXT PRIMARY KEY, -- Format: metric-date
    metric TEXT NOT NULL,
    value REAL NOT NULL,
    dimensions TEXT NOT NULL, -- JSON object with metric dimensions
    date TEXT NOT NULL, -- YYYY-MM-DD format
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Hourly Metrics Table (Aggregated)
CREATE TABLE IF NOT EXISTS hourly_metrics (
    id TEXT PRIMARY KEY, -- Format: metric-date-hour
    metric TEXT NOT NULL,
    value REAL NOT NULL,
    dimensions TEXT NOT NULL, -- JSON object with metric dimensions
    date_hour TEXT NOT NULL, -- YYYY-MM-DD-HH format
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- User Activity Summary Table
CREATE TABLE IF NOT EXISTS user_activity_summary (
    user_id TEXT PRIMARY KEY,
    last_activity TEXT NOT NULL,
    daily_events INTEGER NOT NULL DEFAULT 0,
    session_count INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Business Metrics Table
CREATE TABLE IF NOT EXISTS business_metrics (
    date TEXT PRIMARY KEY, -- YYYY-MM-DD format
    bookings_created INTEGER NOT NULL DEFAULT 0,
    revenue REAL NOT NULL DEFAULT 0,
    chats_started INTEGER NOT NULL DEFAULT 0,
    profile_views INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Notification Results Table
CREATE TABLE IF NOT EXISTS notification_results (
    id TEXT PRIMARY KEY,
    notification_id TEXT NOT NULL,
    channel TEXT NOT NULL CHECK (channel IN ('push', 'email', 'sms', 'in_app', 'all')),
    status TEXT NOT NULL CHECK (status IN ('sent', 'failed', 'pending', 'skipped')),
    delivered_at TEXT,
    error TEXT,
    external_id TEXT, -- ID from external service (FCM, SendGrid, etc.)
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- In-App Notifications Table
CREATE TABLE IF NOT EXISTS in_app_notifications (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    data TEXT, -- JSON object with notification data
    priority TEXT NOT NULL CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- User Devices Table (for push notifications)
CREATE TABLE IF NOT EXISTS user_devices (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    device_type TEXT NOT NULL CHECK (device_type IN ('ios', 'android', 'web')),
    push_tokens TEXT, -- JSON array of push tokens
    device_info TEXT, -- JSON object with device information
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create indexes for better performance

-- Moderation Results Indexes
CREATE INDEX IF NOT EXISTS idx_moderation_results_user_id ON moderation_results(user_id);
CREATE INDEX IF NOT EXISTS idx_moderation_results_content_id ON moderation_results(content_id);
CREATE INDEX IF NOT EXISTS idx_moderation_results_created_at ON moderation_results(created_at);
CREATE INDEX IF NOT EXISTS idx_moderation_results_action ON moderation_results(action);

-- Flagged Content Indexes
CREATE INDEX IF NOT EXISTS idx_flagged_content_content_id ON flagged_content(content_id);
CREATE INDEX IF NOT EXISTS idx_flagged_content_flagged_at ON flagged_content(flagged_at);
CREATE INDEX IF NOT EXISTS idx_flagged_content_resolved_at ON flagged_content(resolved_at);

-- Manual Review Queue Indexes
CREATE INDEX IF NOT EXISTS idx_manual_review_queue_status ON manual_review_queue(status);
CREATE INDEX IF NOT EXISTS idx_manual_review_queue_priority ON manual_review_queue(priority);
CREATE INDEX IF NOT EXISTS idx_manual_review_queue_assigned_to ON manual_review_queue(assigned_to);
CREATE INDEX IF NOT EXISTS idx_manual_review_queue_created_at ON manual_review_queue(created_at);

-- Analytics Events Indexes
CREATE INDEX IF NOT EXISTS idx_analytics_events_user_id ON analytics_events(user_id);
CREATE INDEX IF NOT EXISTS idx_analytics_events_event_type ON analytics_events(event_type);
CREATE INDEX IF NOT EXISTS idx_analytics_events_timestamp ON analytics_events(timestamp);
CREATE INDEX IF NOT EXISTS idx_analytics_events_session_id ON analytics_events(session_id);

-- Daily Metrics Indexes
CREATE INDEX IF NOT EXISTS idx_daily_metrics_metric ON daily_metrics(metric);
CREATE INDEX IF NOT EXISTS idx_daily_metrics_date ON daily_metrics(date);
CREATE INDEX IF NOT EXISTS idx_daily_metrics_metric_date ON daily_metrics(metric, date);

-- Hourly Metrics Indexes
CREATE INDEX IF NOT EXISTS idx_hourly_metrics_metric ON hourly_metrics(metric);
CREATE INDEX IF NOT EXISTS idx_hourly_metrics_date_hour ON hourly_metrics(date_hour);
CREATE INDEX IF NOT EXISTS idx_hourly_metrics_metric_date_hour ON hourly_metrics(metric, date_hour);

-- User Activity Summary Indexes
CREATE INDEX IF NOT EXISTS idx_user_activity_summary_last_activity ON user_activity_summary(last_activity);
CREATE INDEX IF NOT EXISTS idx_user_activity_summary_updated_at ON user_activity_summary(updated_at);

-- Business Metrics Indexes
CREATE INDEX IF NOT EXISTS idx_business_metrics_date ON business_metrics(date);

-- Notification Results Indexes
CREATE INDEX IF NOT EXISTS idx_notification_results_notification_id ON notification_results(notification_id);
CREATE INDEX IF NOT EXISTS idx_notification_results_channel ON notification_results(channel);
CREATE INDEX IF NOT EXISTS idx_notification_results_status ON notification_results(status);
CREATE INDEX IF NOT EXISTS idx_notification_results_created_at ON notification_results(created_at);

-- In-App Notifications Indexes
CREATE INDEX IF NOT EXISTS idx_in_app_notifications_user_id ON in_app_notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_in_app_notifications_is_read ON in_app_notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_in_app_notifications_created_at ON in_app_notifications(created_at);
CREATE INDEX IF NOT EXISTS idx_in_app_notifications_user_unread ON in_app_notifications(user_id, is_read) WHERE is_read = FALSE;

-- User Devices Indexes
CREATE INDEX IF NOT EXISTS idx_user_devices_user_id ON user_devices(user_id);
CREATE INDEX IF NOT EXISTS idx_user_devices_is_active ON user_devices(is_active);
CREATE INDEX IF NOT EXISTS idx_user_devices_device_type ON user_devices(device_type);

-- Add notification preferences column to users table if it doesn't exist
-- This will be handled by a separate migration or ALTER statement
-- ALTER TABLE users ADD COLUMN notification_preferences TEXT DEFAULT '{"push":true,"email":true,"sms":false,"in_app":true}';

-- Add suspension fields to users table if they don't exist
-- ALTER TABLE users ADD COLUMN suspension_end TEXT;
-- ALTER TABLE users ADD COLUMN suspension_reason TEXT;

-- ---- end: 004_background_jobs_tables.sql ----

-- ---- begin: 005_muse_ai_foundation.sql (sha256: 8f898066af3dcad79b56bfd3f397d6066ec3d7b8f66b6dbf1cc4ef2f7066bd5f) ----
-- Migration 005: Muse AI foundation
-- Adds consent, session, preference, recommendation, and privacy request tables.

CREATE TABLE IF NOT EXISTS ai_consent_events (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    session_id TEXT,
    consent_type TEXT NOT NULL CHECK (consent_type IN ('age_gate', 'ai_personalization', 'profile_assist', 'recommendation_retention', 'privacy_terms')),
    action TEXT NOT NULL CHECK (action IN ('granted', 'revoked', 'updated')),
    policy_version TEXT NOT NULL,
    birth_date_year INTEGER,
    is_adult BOOLEAN,
    metadata TEXT DEFAULT '{}',
    ip_address TEXT,
    user_agent TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS muse_sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    anonymous_id TEXT,
    user_role TEXT CHECK (user_role IN ('traveller', 'companion', 'admin')),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'expired', 'revoked')),
    entry_surface TEXT NOT NULL DEFAULT 'muse_home',
    consent_snapshot TEXT DEFAULT '{}',
    locale TEXT DEFAULT 'en',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TEXT
);

CREATE TABLE IF NOT EXISTS muse_messages (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES muse_sessions(id) ON DELETE CASCADE,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    sender TEXT NOT NULL CHECK (sender IN ('user', 'muse', 'system')),
    message_type TEXT NOT NULL DEFAULT 'text' CHECK (message_type IN ('text', 'intent', 'recommendation', 'profile_assist', 'system')),
    content TEXT,
    metadata TEXT DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS muse_preference_profiles (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES muse_sessions(id) ON DELETE CASCADE,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    city_context TEXT,
    travel_context TEXT,
    intent_tags TEXT NOT NULL DEFAULT '[]',
    attraction_qualities TEXT NOT NULL DEFAULT '[]',
    experience_tags TEXT NOT NULL DEFAULT '[]',
    language_preferences TEXT NOT NULL DEFAULT '[]',
    safety_preferences TEXT NOT NULL DEFAULT '[]',
    explanation TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recommendation_runs (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES muse_sessions(id) ON DELETE CASCADE,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    preference_profile_id TEXT REFERENCES muse_preference_profiles(id) ON DELETE SET NULL,
    engine_version TEXT NOT NULL,
    engine_mode TEXT NOT NULL DEFAULT 'deterministic' CHECK (engine_mode IN ('deterministic', 'ai_assisted', 'manual')),
    input_summary TEXT,
    safety_filters TEXT NOT NULL DEFAULT '[]',
    status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('queued', 'completed', 'failed', 'redacted')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recommendation_items (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES recommendation_runs(id) ON DELETE CASCADE,
    item_type TEXT NOT NULL CHECK (item_type IN ('companion', 'experience', 'city', 'safety_note', 'next_step')),
    item_id TEXT,
    rank INTEGER NOT NULL,
    fit_score REAL,
    reason_codes TEXT NOT NULL DEFAULT '[]',
    explanation TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS privacy_requests (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    session_id TEXT REFERENCES muse_sessions(id) ON DELETE SET NULL,
    request_type TEXT NOT NULL CHECK (request_type IN ('export', 'delete', 'revoke_ai', 'correct_profile')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_review', 'completed', 'rejected')),
    requested_payload TEXT DEFAULT '{}',
    operator_notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_ai_consent_events_user_id ON ai_consent_events(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_consent_events_session_id ON ai_consent_events(session_id);
CREATE INDEX IF NOT EXISTS idx_ai_consent_events_type_created ON ai_consent_events(consent_type, created_at);

CREATE INDEX IF NOT EXISTS idx_muse_sessions_user_id ON muse_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_muse_sessions_anonymous_id ON muse_sessions(anonymous_id);
CREATE INDEX IF NOT EXISTS idx_muse_sessions_status ON muse_sessions(status);

CREATE INDEX IF NOT EXISTS idx_muse_messages_session_id ON muse_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_muse_messages_created_at ON muse_messages(created_at);

CREATE INDEX IF NOT EXISTS idx_muse_preference_profiles_session_id ON muse_preference_profiles(session_id);
CREATE INDEX IF NOT EXISTS idx_muse_preference_profiles_user_id ON muse_preference_profiles(user_id);

CREATE INDEX IF NOT EXISTS idx_recommendation_runs_session_id ON recommendation_runs(session_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_runs_user_id ON recommendation_runs(user_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_items_run_id ON recommendation_items(run_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_items_rank ON recommendation_items(run_id, rank);

CREATE INDEX IF NOT EXISTS idx_privacy_requests_user_id ON privacy_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_privacy_requests_status ON privacy_requests(status);

-- ---- end: 005_muse_ai_foundation.sql ----

-- ---- begin: 006_referrals_tirak_coins.sql (sha256: dab4a56f1f78022982601cf6cd018a813660c73f9572713e4ad0cfe833c2130d) ----
-- Migration 006: Referrals and Tirak Coins

CREATE TABLE IF NOT EXISTS referral_accounts (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    referral_code TEXT UNIQUE NOT NULL,
    referred_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    coin_balance INTEGER NOT NULL DEFAULT 0,
    total_earned INTEGER NOT NULL DEFAULT 0,
    total_redeemed INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS referral_events (
    id TEXT PRIMARY KEY,
    referrer_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    referred_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    referral_code TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'awarded' CHECK (status IN ('pending', 'awarded', 'reversed')),
    coins_awarded INTEGER NOT NULL DEFAULT 100,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TEXT,
    UNIQUE(referred_user_id)
);

CREATE TABLE IF NOT EXISTS coin_transactions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL,
    transaction_type TEXT NOT NULL CHECK (transaction_type IN ('referral_bonus', 'redemption', 'admin_adjustment')),
    reason TEXT NOT NULL,
    related_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    referral_event_id TEXT REFERENCES referral_events(id) ON DELETE SET NULL,
    metadata TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_referral_accounts_code ON referral_accounts(referral_code);
CREATE INDEX IF NOT EXISTS idx_referral_events_referrer ON referral_events(referrer_id);
CREATE INDEX IF NOT EXISTS idx_referral_events_referred ON referral_events(referred_user_id);
CREATE INDEX IF NOT EXISTS idx_coin_transactions_user ON coin_transactions(user_id);

-- ---- end: 006_referrals_tirak_coins.sql ----

-- ---- begin: 007_registration_profile_persistence.sql (sha256: 79d7b7a94d9cd40d9e161191f293cc143e68f8aa3132bc727f3072c6e1b1857f) ----
-- Persist mobile registration and companion setup fields.
-- These fields back the current traveler and local-guide onboarding/edit flows.

ALTER TABLE supplier_profiles ADD COLUMN first_name TEXT;
ALTER TABLE supplier_profiles ADD COLUMN last_name TEXT;
ALTER TABLE supplier_profiles ADD COLUMN cover_photo TEXT;
ALTER TABLE supplier_profiles ADD COLUMN location TEXT;
ALTER TABLE supplier_profiles ADD COLUMN social_links TEXT DEFAULT '{}';
ALTER TABLE supplier_profiles ADD COLUMN date_of_birth TEXT;
ALTER TABLE supplier_profiles ADD COLUMN gender TEXT CHECK (gender IN ('male', 'female', 'other'));
ALTER TABLE supplier_profiles ADD COLUMN certifications TEXT DEFAULT '[]';
ALTER TABLE supplier_profiles ADD COLUMN experience_stats TEXT DEFAULT '{}';

ALTER TABLE customer_profiles ADD COLUMN bio TEXT;

-- ---- end: 007_registration_profile_persistence.sql ----
